inherit_from:
  - .rubocop_airbnb.yml

# Rails用に最適化
Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'test/**/*'
    - 'spec/**/*'
    - 'client/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - !ruby/regexp /old_and_unused\.rb$/